require("dotenv").config();

const DATABASE_URL = process.env.REACT_APP_DATABASE_URL;
const EMAIL_SERVICE_ID = process.env.REACT_APP_EMAIL_SERVICE_ID;
const EMAIL_TEMPLATE_ID = process.env.REACT_APP_EMAIL_TEMPLATE_ID;
const EMAIL_USER_ID = process.env.REACT_APP_EMAIL_USER_ID;

const AUTH0_DOMAIN_NAME = process.env.REACT_APP_AUTH0_DOMAIN_NAME;
const AUTH0_CLIENT_ID = process.env.REACT_APP_AUTH0_CLIENT_ID;
const AUTH0_AUDIENCE = process.env.REACT_APP_AUTH0_AUDIENCE;
const AUTH0_SCOPE = process.env.REACT_APP_AUTH0_SCOPE;

const AUTH0_DATABASE_CONNECTION = process.env.REACT_APP_AUTH0_DATABASE_CONNECTION;

module.exports = {
  DATABASE_URL,
  EMAIL_SERVICE_ID,
  EMAIL_TEMPLATE_ID,
  EMAIL_USER_ID,
  AUTH0_DOMAIN_NAME,
  AUTH0_CLIENT_ID,
  AUTH0_AUDIENCE,
  AUTH0_SCOPE,
  AUTH0_DATABASE_CONNECTION
};
